//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Frame
    {
        public string session_hash { get; set; }
        public long timestamp { get; set; }
        public long is_local_device { get; set; }
        public string serialized_object { get; set; }
    
        public virtual Session Session { get; set; }
    }
}
