//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Session()
        {
            this.Frame = new HashSet<Frame>();
        }
    
        public string session_hash { get; set; }
        public string athlete_hash { get; set; }
        public double treadmill_speed { get; set; }
        public long saved { get; set; }
        public string date { get; set; }
        public long height { get; set; }
        public long duration { get; set; }
        public double weight { get; set; }
        public long footwear { get; set; }
        public string pathtoframes { get; set; }
    
        public virtual Athlete Athlete { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Frame> Frame { get; set; }
    }
}
